"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Button } from "./ui/button";
import DisplayTechIcons from "./DisplayTechIcons";
import { cn, getRandomInterviewCover } from "@/lib/utils";
import { createInterview } from "@/lib/actions/general.action";
import { Clock, BarChart } from "lucide-react";

interface TemplateInterviewCardProps {
  userId: string;
  role: string;
  focus: string;
  level: string;
  duration: string;
  techstack: string[];
  type: string;
}

const TemplateInterviewCard = ({
  userId,
  role,
  focus,
  level,
  duration,
  techstack,
  type,
}: TemplateInterviewCardProps) => {
  const router = useRouter();

  const handleStart = async () => {
    const loadingToast = toast.loading("Preparing your interview...");
    
    try {
      const result = await createInterview({
        role,
        level,
        techstack: techstack.join(", "),
        type,
        userId,
        status: "in-progress",
        questions: [], // Will be generated by Gemini
      });

      toast.dismiss(loadingToast);

      if (result.success) {
        toast.success("Starting interview...");
        router.push(`/interview/${result.id}`);
      } else {
        toast.error(result.message || "Failed to start interview");
      }
    } catch (error) {
      console.error("Error starting template interview:", error);
      toast.dismiss(loadingToast);
      toast.error("An error occurred");
    }
  };

  const badgeColor =
    {
      Behavioral: "bg-light-400",
      Mixed: "bg-light-600",
      Technical: "bg-light-800",
    }[type] || "bg-light-600";

  return (
    <div className="card-border w-[360px] max-sm:w-full min-h-96 relative">
      <div className="card-interview">
        <div>
          {/* Type Badge */}
          <div
            className={cn(
              "absolute top-0 right-0 w-fit px-4 py-2 rounded-bl-lg",
              badgeColor
            )}
          >
            <p className="badge-text ">{type}</p>
          </div>

          {/* Cover Image */}
          <Image
            src={getRandomInterviewCover()}
            alt="cover-image"
            width={90}
            height={90}
            className="rounded-full object-fit size-[90px]"
          />

          {/* Interview Role */}
          <h3 className="mt-5 capitalize">{role}</h3>
          
          {/* Focus */}
          <p className="text-sm text-primary-200 mt-1 font-medium">{focus}</p>

          {/* Level & Duration */}
          <div className="flex flex-row gap-5 mt-4">
            <div className="flex flex-row gap-2 items-center">
              <BarChart size={18} className="text-light-400" />
              <p className="text-sm">{level}</p>
            </div>

            <div className="flex flex-row gap-2 items-center">
              <Clock size={18} className="text-light-400" />
              <p className="text-sm">{duration}</p>
            </div>
          </div>

          {/* Description Placeholder */}
          <p className="line-clamp-2 mt-5 text-light-400 text-sm">
            Practice this {role.toLowerCase()} interview to sharpen your skills in {focus.toLowerCase()}.
          </p>
        </div>

        <div className="flex flex-row justify-between items-end mt-auto">
          <DisplayTechIcons techStack={techstack} />

          <Button onClick={handleStart} className="btn-primary">
            Start Interview
          </Button>
        </div>
      </div>
    </div>
  );
};

export default TemplateInterviewCard;
